#ifndef _ESP32_RGB_64_32_MATRIX_PANEL_I2S_DMA
#define _ESP32_RGB_64_32_MATRIX_PANEL_I2S_DMA

/***************************************************************************************/
/* Core ESP32 hardware / IDF includes                                                  */
#include <vector>
#include <memory>
#include <algorithm>
#include <driver/gpio.h>
#include <esp_err.h>
#include <esp_log.h>
#include "esp_attr.h"
#include "esp_heap_caps.h"

// #include <Arduino.h>
#include "platforms/platform_detect.hpp"

/***************************************************************************************/
// CIE 1931 lightness lookup tables - auto-generated by tools/generate_cie_luts.py
// Based on:
//   - https://ledshield.wordpress.com/2012/11/13/led-brightness-to-your-eye-gamma-correction-no/
//   - https://gist.github.com/mathiasvr/19ce1d7b6caeab230934080ae1f1380e
//
// Contains native bit-depth LUTs (6, 7, 8, 10, 12-bit) for optimal performance and quality.
#include "cie_luts.h"

/***************************************************************************************/
// MATRIX_WIDTH and MATRIX_HEIGHT are legacy defines that were originally intended
// to specify individual panel dimensions. However, in many external projects, 
// these defines specify the entire chained matrix size instead.
//
// To prevent macro name collisions while maintaining backward compatibility,
// default aliases are provided unless NEW_MATRIXPANEL_API is defined before including.
// Reference: https://github.com/marcmerlin/FastLED_ESP32-HUB75-MatrixPanel_FrameBuffer_GFX/
#ifndef NEW_MATRIXPANEL_API
#ifdef MATRIX_WIDTH
#define RGB_PANEL_WIDTH MATRIX_WIDTH
#endif
#ifdef MATRIX_HEIGHT
#define RGB_PANEL_HEIGHT MATRIX_HEIGHT
#endif
#endif

#ifdef USE_GFX_LITE
  // Slimmed version of Adafruit GFX + FastLED: https://github.com/mrcodetastic/GFX_Lite
  #include "GFX_Lite.h" 
#elif !defined NO_GFX
  #include "Adafruit_GFX.h" // Adafruit class with graphics utilities
#endif

/*******************************************************************************************
 * COMPILE-TIME OPTIONS - MUST BE PROVIDED as part of PlatformIO project build_flags.      *
 * Changing these values within this scope alone will not persist across compilation.      *
 *******************************************************************************************/
/* Do NOT build additional methods optimized for fast drawing (e.g. drawFastHLine, drawFastVLine) */
// #define NO_FAST_FUNCTIONS

// #define NO_CIE1931

/* Physical / Chained HUB75 RGB panel pixel WIDTH and HEIGHT.
 *
 * Tested with 64x32 and 64x64 RGB panels. To chain two or more horizontally 
 * (e.g., creating a 128x32 panel), link via ribbon cable and set CHAIN_LENGTH to '2'.
 *
 * For a 64x64 panel, set RGB_PANEL_HEIGHT to '64' and allocate an E_PIN.
 * Memory permitting based on sketch hardware usage.
 */
#ifndef RGB_PANEL_WIDTH
#define RGB_PANEL_WIDTH 64 // Single panel width in pixels
#endif

#ifndef RGB_PANEL_HEIGHT
#define RGB_PANEL_HEIGHT 32 // Set to 64 if using a 64px high panel with E_PIN
#endif

#ifndef CHAIN_LENGTH
#define CHAIN_LENGTH 1 // Number of modules chained (e.g., 4 panels = 256px virtual matrix)
#endif

// Note: A uint16_t is used for parallel transmission to the HUB75 interface, but
//       as only 14 physical output wires/bits are mapped, 2 bits remain unused.

/***************************************************************************************/
/* Hardware definitions - modifying these requires altering lower-level library logic. */

// Check for legacy parallel row configuration
#ifdef MATRIX_ROWS_IN_PARALLEL
#pragma message "MATRIX_ROWS_IN_PARALLEL should not be manually set. Resetting to default."
#undef MATRIX_ROWS_IN_PARALLEL
#endif
#define MATRIX_ROWS_IN_PARALLEL 2

// 8 bits per RGB color channel = 24 bits/pixel.
// Can be adjusted to balance color depth and DMA RAM footprint.
#ifdef PIXEL_COLOUR_DEPTH_BITS
#define PIXEL_COLOR_DEPTH_BITS PIXEL_COLOUR_DEPTH_BITS
#endif

// Backward compatibility fallbacks
#ifdef PIXEL_COLOR_DEPTH_BITS
#define PIXEL_COLOR_DEPTH_BITS_DEFAULT PIXEL_COLOR_DEPTH_BITS
#else
#define PIXEL_COLOR_DEPTH_BITS_DEFAULT 8
#endif

#define PIXEL_COLOR_DEPTH_BITS_MAX 12

/***************************************************************************************/
/* Internal data bitmasks and layout offsets                                           */
using ESP32_I2S_DMA_STORAGE_TYPE = uint16_t; // DMA outputs one uint16_t word per clock pulse
constexpr uint8_t CLKS_DURING_LATCH = 0;     // Reserved for future timing adjustments

// Panel Upper Half RGB offsets
constexpr uint16_t BITS_RGB1_OFFSET = 0; 
constexpr uint16_t BIT_R1 = (1 << 0);
constexpr uint16_t BIT_G1 = (1 << 1);
constexpr uint16_t BIT_B1 = (1 << 2);

// Panel Lower Half RGB offsets
constexpr uint16_t BITS_RGB2_OFFSET = 3; 
constexpr uint16_t BIT_R2 = (1 << 3);
constexpr uint16_t BIT_G2 = (1 << 4);
constexpr uint16_t BIT_B2 = (1 << 5);

// Panel Control Signals
constexpr uint16_t BIT_LAT = (1 << 6);
constexpr uint16_t BIT_OE  = (1 << 7);

// Panel Address Pins (A, B, C, D, E)
constexpr uint16_t BITS_ADDR_OFFSET = 8; 
constexpr uint16_t BIT_A = (1 << 8);
constexpr uint16_t BIT_B = (1 << 9);
constexpr uint16_t BIT_C = (1 << 10);
constexpr uint16_t BIT_D = (1 << 11);
constexpr uint16_t BIT_E = (1 << 12);

// Pre-calculated Bitmasks for fast pixel update operations
constexpr uint16_t BITMASK_RGB1_CLEAR  = 0xFFF8; // Inverted bitmask clearing R1G1B1
constexpr uint16_t BITMASK_RGB2_CLEAR  = 0xFFC7; // Inverted bitmask clearing R2G2B2
constexpr uint16_t BITMASK_RGB12_CLEAR = 0xFFC0; // Inverted bitmask clearing R1G1B1R2G2B2
constexpr uint16_t BITMASK_CTRL_CLEAR  = 0xE03F; // Inverted bitmask clearing control signals (ABCDE, LAT, OE)
constexpr uint16_t BITMASK_OE_CLEAR    = 0xFF7F; // Inverted bitmask clearing Output Enable (OE)

// Output Enable (OE) blanking duration around LAT signal pulses
constexpr uint8_t DEFAULT_LAT_BLANKING = 2;
constexpr uint8_t MAX_LAT_BLANKING = 8;

/***************************************************************************************/
// Check compile-time only options
#if PIXEL_COLOR_DEPTH_BITS > 8
    #error "Pixel color depth bits cannot be greater than 8."
#elif PIXEL_COLOR_DEPTH_BITS < 2 
    #error "Pixel color depth bits cannot be less than 2."
#endif

/* This library is designed to take an 8 bit / 1 byte value (0-255) for each R G B colour sub-pixel. 
 * The PIXEL_COLOR_DEPTH_BITS should always be '8' as a result.
 * However, if the library is to be used with lower colour depth (i.e. 6 bit colour), then we need to ensure the 8-bit value passed to the colour masking
 * is adjusted accordingly to ensure the LSB's are shifted left to MSB, by the difference. Otherwise the colours will be all screwed up.
 */
#if PIXEL_COLOR_DEPTH_BITS != 8
static constexpr uint8_t const MASK_OFFSET = 8-PIXEL_COLOR_DEPTH_BITS;
#endif

/***************************************************************************************/

/**
 * Custom memory deleter for ESP32 heap capabilities (e.g. DMA, SPIRAM).
 */
struct HeapCapsDeleter {
    void operator()(void* ptr) const {
        if (ptr) {
            heap_caps_free(ptr);
        }
    }
};

template <typename T>
using dma_unique_ptr = std::unique_ptr<T[], HeapCapsDeleter>;


/** 
 * @struct rowBitStruct
 * @brief Raw DMA data structure driving TWO full pixel rows across chained modules.
 *
 * @var width Width of the row in pixels
 * @var colour_depth Bit depth layers (copies of each row per color bitplane)
 * @var data Pointer to DMA memory array holding pixel color payload
 * 
 * @note Memory alignment varies by target device and configuration:
 * - ESP32-S3 with SPIRAM: Word-aligned block allocated in SPIRAM
 * - Default targets: Allocated in DMA-capable internal RAM
 */
struct rowBitStruct {
    const size_t width;
    const uint8_t colour_depth;
    dma_unique_ptr<ESP32_I2S_DMA_STORAGE_TYPE> data;

    /** 
     * @brief Calculates DMA row data array memory requirements in bytes.
     * @param single_color_depth If true, returns size for 1 bitplane layer; if false, for all layers.
     */
    [[nodiscard]] size_t getColorDepthSize(bool single_color_depth) const noexcept {
        int _cdepth = single_color_depth ? 1 : colour_depth;
        return width * _cdepth * sizeof(ESP32_I2S_DMA_STORAGE_TYPE);
    }

    /** 
     * @brief Returns a pointer to the row data vector starting at pixel[0] for a specific color bitplane depth.
     */
    [[nodiscard]] inline ESP32_I2S_DMA_STORAGE_TYPE* getDataPtr(const uint8_t depth = 0) const noexcept { 
        return &(data[depth * width]); 
    }

    // Constructor: Allocates DMA-capable memory block for struct storage
    rowBitStruct(const size_t _width, const uint8_t _depth) 
        : width(_width), colour_depth(_depth), data(nullptr)
    {
        size_t bytes = getColorDepthSize(false);
#if defined(SPIRAM_DMA_BUFFER)
        auto* raw_ptr = static_cast<ESP32_I2S_DMA_STORAGE_TYPE*>(
            heap_caps_aligned_alloc(64, bytes, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT));
#else
        auto* raw_ptr = static_cast<ESP32_I2S_DMA_STORAGE_TYPE*>(
            heap_caps_malloc(bytes, MALLOC_CAP_INTERNAL | MALLOC_CAP_DMA));
#endif
        data.reset(raw_ptr);
    }

    ~rowBitStruct() = default;

    // Explicit non-copyable semantic contract (Rule of Five)
    rowBitStruct(const rowBitStruct&) = delete;
    rowBitStruct& operator=(const rowBitStruct&) = delete;

    rowBitStruct(rowBitStruct&&) noexcept = default;
    rowBitStruct& operator=(rowBitStruct&&) noexcept = default;
};

/**
 * @struct frameStruct
 * @brief Holds full-frame data across parallel sub-rows.
 *
 * @note Managed row-by-row via individual rowBits pointers.
 */
struct frameStruct {
    uint8_t rows = 0; // Active row count in current frame
    std::vector<std::unique_ptr<rowBitStruct>> rowBits;
};

/***************************************************************************************/
// CIE 1931 lightness lookup tables - generated via tools/generate_cie_luts.py
// References:
//   - https://ledshield.wordpress.com/2012/11/13/led-brightness-to-your-eye-gamma-correction-no/
//   - https://gist.github.com/mathiasvr/19ce1d7b6caeab230934080ae1f1380e
#include "cie_luts.h"

/** 
 * @struct HUB75_I2S_CFG
 * @brief Configuration parameter structure for HUB75 I2S initialization.
 */
struct HUB75_I2S_CFG {

    // Standard unscoped enums for 100% backward compatibility with legacy user sketches
    enum shift_driver {
        SHIFTREG = 0,
        FM6124,
        FM6126A,
        ICN2038S,
        MBI5124,
        DP3246
    };

    enum line_driver {
        TYPE138 = 0,    
        TYPE595,        
        TYPE_DIRECT,    
        SM5266P,        
        SM5368 = TYPE595
    };

    enum clk_speed {
        HZ_8M = 8000000,
        HZ_10M = 8000000,
        HZ_15M = 16000000, 
        HZ_16M = 16000000,
        HZ_20M = 20000000 
    };

    uint16_t mx_width;       
    uint16_t mx_height;      
    uint16_t chain_length;   

    struct i2s_pins {
        int8_t r1, g1, b1, r2, g2, b2, a, b, c, d, e, lat, oe, clk;
    } gpio;

    shift_driver driver;
    line_driver line_decoder;
    bool double_buff;
    clk_speed i2sspeed;
    uint8_t latch_blanking;

    bool clkphase;
    uint16_t min_refresh_rate;

    HUB75_I2S_CFG(
        uint16_t _w = RGB_PANEL_WIDTH,
        uint16_t _h = RGB_PANEL_HEIGHT,
        uint16_t _chain = CHAIN_LENGTH,
        i2s_pins _pinmap = {
            R1_PIN_DEFAULT, G1_PIN_DEFAULT, B1_PIN_DEFAULT, 
            R2_PIN_DEFAULT, G2_PIN_DEFAULT, B2_PIN_DEFAULT,
            A_PIN_DEFAULT, B_PIN_DEFAULT, C_PIN_DEFAULT, 
            D_PIN_DEFAULT, E_PIN_DEFAULT,
            LAT_PIN_DEFAULT, OE_PIN_DEFAULT, CLK_PIN_DEFAULT},
        shift_driver _drv = SHIFTREG, 
        line_driver _line_drv = TYPE138,
        bool _dbuff = false, 
        clk_speed _i2sspeed = HZ_8M,
        uint8_t _latblk = 0, // 0 = Auto-calculate based on clock speed
        bool _clockphase = true, 
        uint16_t _min_refresh_rate = 60, 
        uint8_t _pixel_color_depth_bits = PIXEL_COLOR_DEPTH_BITS_DEFAULT) 
        : mx_width(_w), mx_height(_h), chain_length(_chain), gpio(_pinmap), driver(_drv), 
          line_decoder(_line_drv), double_buff(_dbuff), i2sspeed(_i2sspeed), 
          clkphase(_clockphase), min_refresh_rate(_min_refresh_rate)
    {
        // Auto-calculate conservative latch blanking margin if left at 0
        if (_latblk == 0) {
            latch_blanking = (static_cast<uint32_t>(i2sspeed) > 10000000UL) ? 8 : 4;
        } else {
            latch_blanking = std::max(static_cast<uint8_t>(1), std::min(_latblk, MAX_LAT_BLANKING));
        }

        setPixelColorDepthBits(_pixel_color_depth_bits);
    }

    void setPixelColorDepthBits(uint8_t _pixel_color_depth_bits) {
        if (_pixel_color_depth_bits > PIXEL_COLOR_DEPTH_BITS_MAX || _pixel_color_depth_bits < 2) {
            pixel_color_depth_bits = (_pixel_color_depth_bits > PIXEL_COLOR_DEPTH_BITS_MAX) ? PIXEL_COLOR_DEPTH_BITS_MAX : 2;
            ESP_LOGW("HUB75_I2S_CFG", "Invalid pixel_color_depth_bits (%d): choosing nearest valid %d", 
                     _pixel_color_depth_bits, pixel_color_depth_bits);
        } else {
            pixel_color_depth_bits = _pixel_color_depth_bits;
        }
    }

    [[nodiscard]] uint8_t getPixelColorDepthBits() const noexcept {
        return pixel_color_depth_bits;
    }

private:
    uint8_t pixel_color_depth_bits;
};


#ifdef USE_GFX_LITE
class MatrixPanel_I2S_DMA : public GFX
#elif !defined NO_GFX
class MatrixPanel_I2S_DMA : public Adafruit_GFX
#else
class MatrixPanel_I2S_DMA
#endif
{
public:
    MatrixPanel_I2S_DMA()
#ifdef USE_GFX_LITE
        : GFX(RGB_PANEL_WIDTH, RGB_PANEL_HEIGHT)
#elif !defined NO_GFX
        : Adafruit_GFX(RGB_PANEL_WIDTH, RGB_PANEL_HEIGHT)
#endif
    {}

    MatrixPanel_I2S_DMA(const HUB75_I2S_CFG &opts)
#ifdef USE_GFX_LITE
        : GFX(opts.mx_width * opts.chain_length, opts.mx_height)
#elif !defined NO_GFX
        : Adafruit_GFX(opts.mx_width * opts.chain_length, opts.mx_height)
#endif
    {
        setCfg(opts);
    }

    bool begin();
    virtual ~MatrixPanel_I2S_DMA() {
        dma_bus.release();
    }

    bool begin(int r1, int g1 = G1_PIN_DEFAULT, int b1 = B1_PIN_DEFAULT, int r2 = R2_PIN_DEFAULT, int g2 = G2_PIN_DEFAULT, int b2 = B2_PIN_DEFAULT, int a = A_PIN_DEFAULT, int b = B_PIN_DEFAULT, int c = C_PIN_DEFAULT, int d = D_PIN_DEFAULT, int e = E_PIN_DEFAULT, int lat = LAT_PIN_DEFAULT, int oe = OE_PIN_DEFAULT, int clk = CLK_PIN_DEFAULT);
    bool begin(const HUB75_I2S_CFG &cfg);

    // Adafruit GFX API draw methods
    virtual void drawPixel(int16_t x, int16_t y, uint16_t color); 
    virtual void fillScreen(uint16_t color);                      

    inline void clearScreen() { updateMatrixDMABuffer(0, 0, 0); }

#ifndef NO_FAST_FUNCTIONS
    virtual void drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color) {
        uint8_t r, g, b;
        color565to888(color, r, g, b);
        int16_t w = 1;
        transform(x, y, w, h);
        if (h > w) vlineDMA(x, y, h, r, g, b);
        else hlineDMA(x, y, w, r, g, b);
    }

    virtual inline void drawFastVLine(int16_t x, int16_t y, int16_t h, uint8_t r, uint8_t g, uint8_t b) {
        int16_t w = 1;
        transform(x, y, w, h);
        if (h > w) vlineDMA(x, y, h, r, g, b);
        else hlineDMA(x, y, w, r, g, b);
    }

    virtual void drawFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color)  {
        uint8_t r, g, b;
        color565to888(color, r, g, b);
        int16_t h = 1;
        transform(x, y, w, h);
        if (h > w) vlineDMA(x, y, h, r, g, b);
        else hlineDMA(x, y, w, r, g, b);
    }

    virtual inline void drawFastHLine(int16_t x, int16_t y, int16_t w, uint8_t r, uint8_t g, uint8_t b) {
        int16_t h = 1;
        transform(x, y, w, h);
        if (h > w) vlineDMA(x, y, h, r, g, b);
        else hlineDMA(x, y, w, r, g, b);
    }

    virtual void fillRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color) {
        uint8_t r, g, b;
        color565to888(color, r, g, b);
        transform(x, y, w, h);
        fillRectDMA(x, y, w, h, r, g, b);
    }

    virtual inline void fillRect(int16_t x, int16_t y, int16_t w, int16_t h, uint8_t r, uint8_t g, uint8_t b) {
        transform(x, y, w, h);
        fillRectDMA(x, y, w, h, r, g, b);
    }
#endif

    void fillScreenRGB888(uint8_t r, uint8_t g, uint8_t b);
    void drawPixelRGB888(int16_t x, int16_t y, uint8_t r, uint8_t g, uint8_t b);

#ifdef USE_GFX_LITE
    void fillScreen(CRGB color);
    void drawPixel(int16_t x, int16_t y, CRGB color);
#endif

#ifdef NO_GFX
    [[nodiscard]] inline int16_t width() const noexcept { return m_cfg.mx_width * m_cfg.chain_length; }
    [[nodiscard]] inline int16_t height() const noexcept { return m_cfg.mx_height; }
#endif

    void drawIcon(int *ico, int16_t x, int16_t y, int16_t cols, int16_t rows);

    static uint16_t color444(uint8_t r, uint8_t g, uint8_t b) { return color565(r * 17, g * 17, b * 17); }
    static uint16_t color565(uint8_t r, uint8_t g, uint8_t b); 
    static void color565to888(const uint16_t color, uint8_t &r, uint8_t &g, uint8_t &b);

    inline void flipDMABuffer() {
        if (!m_cfg.double_buff) return;
        dma_bus.flip_dma_output_buffer(back_buffer_id);
        back_buffer_id ^= 1;
        fb = &frame_buffer[back_buffer_id];  
    }

    void setBrightness(const uint8_t b) {
        if (!initialized) {
            ESP_LOGI("setBrightness()", "Tried to set output brightness before begin()");
            return;
        }
        brightness = b;
        setBrightnessOE(b, 0);
        if (m_cfg.double_buff) {
            setBrightnessOE(b, 1);
        }
    }

    void setPanelBrightness(const uint8_t b) { setBrightness(b); }
    void setBrightness8(const uint8_t b) { setBrightness(b); }
    uint8_t setLatBlanking(uint8_t pulses);

    [[nodiscard]] const HUB75_I2S_CFG &getCfg() const noexcept { return m_cfg; }

    inline bool setCfg(const HUB75_I2S_CFG &cfg) {
        if (initialized) return false;

        m_cfg = cfg;
        PIXELS_PER_ROW = m_cfg.mx_width * m_cfg.chain_length;
        ROWS_PER_FRAME = m_cfg.mx_height / MATRIX_ROWS_IN_PARALLEL;
        MASK_OFFSET = 16 - m_cfg.getPixelColorDepthBits();

        config_set = true;
        return true;
    }

    void stopDMAoutput() {
        resetbuffers();
        dma_bus.dma_transfer_stop();
    }

    void resumeDMAoutput() {
        dma_bus.dma_transfer_start();
    }

protected:
    void clearFrameBuffer(bool _buff_id);
    void updateMatrixDMABuffer(uint16_t x, uint16_t y, uint8_t red, uint8_t green, uint8_t blue);
    void updateMatrixDMABuffer(uint8_t red, uint8_t green, uint8_t blue);

    inline void resetbuffers() {
        clearFrameBuffer(0);        
        setBrightnessOE(brightness, 0); 

        if (m_cfg.double_buff) {
            clearFrameBuffer(1);        
            setBrightnessOE(brightness, 1);
        }
    }

#ifndef NO_FAST_FUNCTIONS
    void hlineDMA(int16_t x_coord, int16_t y_coord, int16_t l, uint8_t red, uint8_t green, uint8_t blue);
    void vlineDMA(int16_t x_coord, int16_t y_coord, int16_t l, uint8_t red, uint8_t green, uint8_t blue);
    void fillRectDMA(int16_t x_coord, int16_t y_coord, int16_t w, int16_t h, uint8_t r, uint8_t g, uint8_t b);
#endif

private:
    // High-level pipeline routines
    bool validateConfiguration() const;
    bool setupDMA(const HUB75_I2S_CFG &opts);

    // Private helpers split out from setupDMA
    bool allocateFrameBuffers(int fbs_required);
    void calculateRefreshRateAndTransitionBit();
    [[nodiscard]] int calculateDmaDescriptorCount(int &dma_descs_per_row_all_cdepths, 
                                                  size_t &last_dma_desc_bytes_all_cdepths, 
                                                  int &dma_descs_per_row_1cdepth, 
                                                  size_t &last_dma_desc_bytes_1cdepth) const;
    void buildDmaDescriptorLinks(int fbs_required, 
                                 int dma_descs_per_row_all_cdepths, 
                                 size_t last_dma_desc_bytes_all_cdepths, 
                                 int dma_descs_per_row_1cdepth, 
                                 size_t last_dma_desc_bytes_1cdepth);
    void configureBusParallel16();

    // Private helpers split out from clearFrameBuffer
    [[nodiscard]] ESP32_I2S_DMA_STORAGE_TYPE calculateRowAddressMask(uint8_t row_idx, ESP32_I2S_DMA_STORAGE_TYPE abcde_mask) const;
    void applyShiftRegisterLineDecoderFixes(frameStruct* target_fb, uint8_t row_idx);
    void applyRowControlPulses(frameStruct* target_fb, uint8_t row_idx);

    void shiftDriver(const HUB75_I2S_CFG &opts);
    void fm6124init(const HUB75_I2S_CFG &_cfg);
    void dp3246init(const HUB75_I2S_CFG& _cfg);
    void setBrightnessOE(uint8_t brt, const int _buff_id = 0);

    void transform(int16_t &x, int16_t &y, int16_t &w, int16_t &h) {
#ifndef NO_GFX
        int16_t t;
        switch (rotation) {
        case 1:
            t = _height - 1 - y - (h - 1);
            y = x;
            x = t;
            t = h;
            h = w;
            w = t;
            return;
        case 2:
            x = _width - 1 - x - (w - 1);
            y = _height - 1 - y - (h - 1);
            return;
        case 3:
            t = y;
            y = _width - 1 - x - (w - 1);
            x = t;
            t = h;
            h = w;
            w = t;
            return;
        }
#endif
    }

    [[nodiscard]] inline ESP32_I2S_DMA_STORAGE_TYPE* getRowDataPtr(uint8_t row, uint8_t depth) const noexcept {
        return fb->rowBits[row]->getDataPtr(depth);
    }

public:
    int calculated_refresh_rate = 0;

protected:
    Bus_Parallel16 dma_bus;

private:
    HUB75_I2S_CFG m_cfg;
    frameStruct frame_buffer[2];
    frameStruct *fb = nullptr;

    volatile int back_buffer_id = 0;      
    int brightness = 128;        
    int lsbMsbTransitionBit = 0; 

    uint16_t PIXELS_PER_ROW = m_cfg.mx_width * m_cfg.chain_length;      
    uint8_t ROWS_PER_FRAME = m_cfg.mx_height / MATRIX_ROWS_IN_PARALLEL; 
    uint8_t MASK_OFFSET = 16 - m_cfg.getPixelColorDepthBits();

    bool initialized = false;
    bool config_set = false;
};

inline void MatrixPanel_I2S_DMA::color565to888(const uint16_t color, uint8_t &r, uint8_t &g, uint8_t &b) {
    r = (color >> 8) & 0xf8;
    g = (color >> 3) & 0xfc;
    b = (color << 3);
    r |= r >> 5;
    g |= g >> 6;
    b |= b >> 5;
}

inline void MatrixPanel_I2S_DMA::drawPixel(int16_t x, int16_t y, uint16_t color) {
    uint8_t r, g, b;
    color565to888(color, r, g, b);
    int16_t w = 1, h = 1;
    transform(x, y, w, h);
    updateMatrixDMABuffer(x, y, r, g, b);
}

inline void MatrixPanel_I2S_DMA::fillScreen(uint16_t color) {
    uint8_t r, g, b;
    color565to888(color, r, g, b);
    updateMatrixDMABuffer(r, g, b); 
}

inline void MatrixPanel_I2S_DMA::drawPixelRGB888(int16_t x, int16_t y, uint8_t r, uint8_t g, uint8_t b) {
    int16_t w = 1, h = 1;
    transform(x, y, w, h);
    updateMatrixDMABuffer(x, y, r, g, b);
}

inline void MatrixPanel_I2S_DMA::fillScreenRGB888(uint8_t r, uint8_t g, uint8_t b) {
    updateMatrixDMABuffer(r, g, b); 
}

#ifdef USE_GFX_LITE
inline void MatrixPanel_I2S_DMA::drawPixel(int16_t x, int16_t y, CRGB color) {
    int16_t w = 1, h = 1;
    transform(x, y, w, h);
    updateMatrixDMABuffer(x, y, color.red, color.green, color.blue);
}

inline void MatrixPanel_I2S_DMA::fillScreen(CRGB color) {
    updateMatrixDMABuffer(color.red, color.green, color.blue);
}
#endif

inline uint16_t MatrixPanel_I2S_DMA::color565(uint8_t r, uint8_t g, uint8_t b) {
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
}

#endif