name: esp-idf with Adafruit GFX Library

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - '.github/**'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Checkout Adafruit-GFX-Library repo
      uses: actions/checkout@v2
      with:
        repository: 'adafruit/Adafruit-GFX-Library'
        path: 'examples/esp-idf/with-gfx/components/Adafruit-GFX-Library'
    - name: Checkout Adafruit_BusIO repo
      uses: actions/checkout@v2
      with:
        repository: 'adafruit/Adafruit_BusIO'
        path: 'examples/esp-idf/with-gfx/components/Adafruit_BusIO'
    - name: Checkout arduino-esp32 repo
      uses: actions/checkout@v2
      with:
        repository: 'espressif/arduino-esp32'
        path: 'examples/esp-idf/with-gfx/components/arduino'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4.4
        target: esp32
        path: 'examples/esp-idf/with-gfx'
